name: jt_app_basic_structure
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
# Package set ==============================================================================================
# ==========================================================================================================
  cupertino_icons: ^1.0.6

  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  go_router: ^14.1.3
  sqflite: ^2.3.3+1
  permission_handler: ^11.1.0
  path: ^1.9.0

  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  animate_do: ^3.3.4
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.0.10+1
  action_slider: ^0.7.0
  sliding_up_panel: ^2.0.0+1

  util_and_style_cores:
    git:
      url: https://github.com/ttesjt/flutter_util_and_style_cores.git
      ref: main
# ==========================================================================================================
# Package set ==============================================================================================

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash/infinite_grows.png
  android: true
  ios: true

  android_12:
    color: "#ffffff"
    image: assets/images/splash/infinite_grows.png

# run: dart run flutter_native_splash:create after modify the splash screen

flutter:

  uses-material-design: true

